name: services
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  shared:
    path: ../shared
  api_models:
    path: ../api_models
  models:
    path: ../models
  firebase_messaging: ^14.7.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
