import 'package:models/models.dart';

class Trakers {
  // weight start
  List<ChartSampleData> weightStandardsForGirls = <ChartSampleData>[
    ChartSampleData(
      index: 0,
      y: 4.8,
      yValue: 2.0,
      secondSeriesYValue: 4.2,
      thirdSeriesYValue: 2.4,
      fourthSeriesYValue: 3.7,
      fifthSeriesYValue: 2.8,
      sixthSeriesYValue: 3.2,
    ),
    ChartSampleData(
      index: 1,
      y: 6.2,
      yValue: 2.7,
      secondSeriesYValue: 5.5,
      thirdSeriesYValue: 3.2,
      fourthSeriesYValue: 4.8,
      fifthSeriesYValue: 3.6,
      sixthSeriesYValue: 4.2,
    ),
    ChartSampleData(
      index: 2,
      y: 7.5,
      yValue: 3.4,
      secondSeriesYValue: 6.6,
      thirdSeriesYValue: 3.9,
      fourthSeriesYValue: 5.8,
      fifthSeriesYValue: 4.5,
      sixthSeriesYValue: 5.1,
    ),
    ChartSampleData(
      index: 3,
      y: 8.5,
      yValue: 4.0,
      secondSeriesYValue: 7.5,
      thirdSeriesYValue: 4.5,
      fourthSeriesYValue: 6.6,
      fifthSeriesYValue: 5.2,
      sixthSeriesYValue: 5.8,
    ),
    ChartSampleData(
      index: 4,
      y: 9.3,
      yValue: 4.4,
      secondSeriesYValue: 8.2,
      thirdSeriesYValue: 5.0,
      fourthSeriesYValue: 7.3,
      fifthSeriesYValue: 5.7,
      sixthSeriesYValue: 6.4,
    ),
    ChartSampleData(
      index: 5,
      y: 10.0,
      yValue: 4.8,
      secondSeriesYValue: 8.8,
      thirdSeriesYValue: 5.4,
      fourthSeriesYValue: 7.8,
      fifthSeriesYValue: 6.1,
      sixthSeriesYValue: 6.9,
    ),
    ChartSampleData(
      index: 6,
      y: 10.6,
      yValue: 5.1,
      secondSeriesYValue: 9.3,
      thirdSeriesYValue: 5.7,
      fourthSeriesYValue: 8.2,
      fifthSeriesYValue: 6.5,
      sixthSeriesYValue: 7.3,
    ),
    ChartSampleData(
      index: 7,
      y: 11.1,
      yValue: 5.3,
      secondSeriesYValue: 9.8,
      thirdSeriesYValue: 6.0,
      fourthSeriesYValue: 8.6,
      fifthSeriesYValue: 6.8,
      sixthSeriesYValue: 7.6,
    ),
    ChartSampleData(
      index: 8,
      y: 11.6,
      yValue: 5.6,
      secondSeriesYValue: 10.2,
      thirdSeriesYValue: 6.3,
      fourthSeriesYValue: 9.0,
      fifthSeriesYValue: 7.0,
      sixthSeriesYValue: 7.9,
    ),
    ChartSampleData(
      index: 9,
      y: 12.0,
      yValue: 5.8,
      secondSeriesYValue: 10.5,
      thirdSeriesYValue: 6.5,
      fourthSeriesYValue: 9.3,
      fifthSeriesYValue: 7.3,
      sixthSeriesYValue: 8.2,
    ),
    ChartSampleData(
      index: 10,
      y: 12.4,
      yValue: 5.9,
      secondSeriesYValue: 10.9,
      thirdSeriesYValue: 6.7,
      fourthSeriesYValue: 9.6,
      fifthSeriesYValue: 7.5,
      sixthSeriesYValue: 8.5,
    ),
    ChartSampleData(
      index: 11,
      y: 12.8,
      yValue: 6.1,
      secondSeriesYValue: 11.2,
      thirdSeriesYValue: 6.9,
      fourthSeriesYValue: 9.9,
      fifthSeriesYValue: 7.7,
      sixthSeriesYValue: 8.7,
    ),
  ];

  List<ChartSampleData> weightStandardsForBoys = <ChartSampleData>[
    ChartSampleData(
      index: 0,
      y: 5.0,
      yValue: 2.1,
      secondSeriesYValue: 4.4,
      thirdSeriesYValue: 2.5,
      fourthSeriesYValue: 3.9,
      fifthSeriesYValue: 2.9,
      sixthSeriesYValue: 3.3,
    ),
    ChartSampleData(
      index: 1,
      y: 6.6,
      yValue: 2.9,
      secondSeriesYValue: 5.8,
      thirdSeriesYValue: 3.4,
      fourthSeriesYValue: 5.1,
      fifthSeriesYValue: 3.9,
      sixthSeriesYValue: 4.5,
    ),
    ChartSampleData(
      index: 2,
      y: 8.0,
      yValue: 3.8,
      secondSeriesYValue: 7.1,
      thirdSeriesYValue: 4.3,
      fourthSeriesYValue: 6.3,
      fifthSeriesYValue: 4.9,
      sixthSeriesYValue: 5.6,
    ),
    ChartSampleData(
      index: 3,
      y: 9.0,
      yValue: 4.4,
      secondSeriesYValue: 8.0,
      thirdSeriesYValue: 5.0,
      fourthSeriesYValue: 7.2,
      fifthSeriesYValue: 5.7,
      sixthSeriesYValue: 6.4,
    ),
    ChartSampleData(
      index: 4,
      y: 9.7,
      yValue: 4.9,
      secondSeriesYValue: 8.7,
      thirdSeriesYValue: 5.6,
      fourthSeriesYValue: 7.8,
      fifthSeriesYValue: 6.2,
      sixthSeriesYValue: 7.0,
    ),
    ChartSampleData(
      index: 5,
      y: 10.4,
      yValue: 5.3,
      secondSeriesYValue: 9.3,
      thirdSeriesYValue: 6.0,
      fourthSeriesYValue: 8.4,
      fifthSeriesYValue: 6.7,
      sixthSeriesYValue: 7.5,
    ),
    ChartSampleData(
      index: 6,
      y: 10.9,
      yValue: 5.7,
      secondSeriesYValue: 9.8,
      thirdSeriesYValue: 6.4,
      fourthSeriesYValue: 8.8,
      fifthSeriesYValue: 7.1,
      sixthSeriesYValue: 7.9,
    ),
    ChartSampleData(
      index: 7,
      y: 11.4,
      yValue: 5.9,
      secondSeriesYValue: 10.3,
      thirdSeriesYValue: 6.7,
      fourthSeriesYValue: 9.2,
      fifthSeriesYValue: 7.4,
      sixthSeriesYValue: 8.3,
    ),
    ChartSampleData(
      index: 8,
      y: 11.9,
      yValue: 6.2,
      secondSeriesYValue: 10.7,
      thirdSeriesYValue: 6.9,
      fourthSeriesYValue: 9.6,
      fifthSeriesYValue: 7.7,
      sixthSeriesYValue: 8.6,
    ),
    ChartSampleData(
      index: 9,
      y: 12.3,
      yValue: 6.4,
      secondSeriesYValue: 11.0,
      thirdSeriesYValue: 7.1,
      fourthSeriesYValue: 9.9,
      fifthSeriesYValue: 8.0,
      sixthSeriesYValue: 8.9,
    ),
    ChartSampleData(
      index: 10,
      y: 12.7,
      yValue: 6.6,
      secondSeriesYValue: 11.4,
      thirdSeriesYValue: 7.4,
      fourthSeriesYValue: 10.2,
      fifthSeriesYValue: 8.2,
      sixthSeriesYValue: 9.2,
    ),
    ChartSampleData(
      index: 11,
      y: 13.0,
      yValue: 6.8,
      secondSeriesYValue: 11.7,
      thirdSeriesYValue: 7.6,
      fourthSeriesYValue: 10.5,
      fifthSeriesYValue: 8.4,
      sixthSeriesYValue: 9.4,
    ),
  ];
  // weight end

  // height start
  List<ChartSampleData> heightStandardsForGirls = <ChartSampleData>[
    ChartSampleData(
      index: 0,
      y: 54.7,
      yValue: 43.6,
      secondSeriesYValue: 52.9,
      thirdSeriesYValue: 45.4,
      fourthSeriesYValue: 51.0,
      fifthSeriesYValue: 47.3,
      sixthSeriesYValue: 49.1,
    ),
    ChartSampleData(
      index: 1,
      y: 59.5,
      yValue: 47.8,
      secondSeriesYValue: 57.6,
      thirdSeriesYValue: 49.8,
      fourthSeriesYValue: 55.6,
      fifthSeriesYValue: 51.7,
      sixthSeriesYValue: 53.7,
    ),
    ChartSampleData(
      index: 2,
      y: 63.2,
      yValue: 51.0,
      secondSeriesYValue: 61.1,
      thirdSeriesYValue: 53.0,
      fourthSeriesYValue: 59.1,
      fifthSeriesYValue: 55.0,
      sixthSeriesYValue: 57.1,
    ),
    ChartSampleData(
      index: 3,
      y: 66.1,
      yValue: 53.5,
      secondSeriesYValue: 64.0,
      thirdSeriesYValue: 55.6,
      fourthSeriesYValue: 61.9,
      fifthSeriesYValue: 57.7,
      sixthSeriesYValue: 59.8,
    ),
    ChartSampleData(
      index: 4,
      y: 68.6,
      yValue: 55.6,
      secondSeriesYValue: 66.4,
      thirdSeriesYValue: 57.8,
      fourthSeriesYValue: 64.3,
      fifthSeriesYValue: 59.9,
      sixthSeriesYValue: 62.1,
    ),
    ChartSampleData(
      index: 5,
      y: 70.7,
      yValue: 57.4,
      secondSeriesYValue: 68.5,
      thirdSeriesYValue: 59.6,
      fourthSeriesYValue: 66.2,
      fifthSeriesYValue: 61.8,
      sixthSeriesYValue: 64.0,
    ),
    ChartSampleData(
      index: 6,
      y: 72.5,
      yValue: 58.9,
      secondSeriesYValue: 70.3,
      thirdSeriesYValue: 61.2,
      fourthSeriesYValue: 68.0,
      fifthSeriesYValue: 63.5,
      sixthSeriesYValue: 65.7,
    ),
    ChartSampleData(
      index: 7,
      y: 74.2,
      yValue: 60.3,
      secondSeriesYValue: 71.9,
      thirdSeriesYValue: 62.7,
      fourthSeriesYValue: 69.6,
      fifthSeriesYValue: 65.0,
      sixthSeriesYValue: 67.3,
    ),
    ChartSampleData(
      index: 8,
      y: 75.8,
      yValue: 61.7,
      secondSeriesYValue: 73.5,
      thirdSeriesYValue: 64.0,
      fourthSeriesYValue: 71.1,
      fifthSeriesYValue: 66.4,
      sixthSeriesYValue: 68.7,
    ),
    ChartSampleData(
      index: 9,
      y: 77.4,
      yValue: 62.9,
      secondSeriesYValue: 75.0,
      thirdSeriesYValue: 65.3,
      fourthSeriesYValue: 72.6,
      fifthSeriesYValue: 67.7,
      sixthSeriesYValue: 70.1,
    ),
    ChartSampleData(
      index: 10,
      y: 78.9,
      yValue: 64.1,
      secondSeriesYValue: 76.4,
      thirdSeriesYValue: 66.5,
      fourthSeriesYValue: 73.9,
      fifthSeriesYValue: 69.0,
      sixthSeriesYValue: 71.5,
    ),
    ChartSampleData(
      index: 11,
      y: 80.3,
      yValue: 65.2,
      secondSeriesYValue: 77.8,
      thirdSeriesYValue: 67.7,
      fourthSeriesYValue: 75.3,
      fifthSeriesYValue: 70.3,
      sixthSeriesYValue: 72.8,
    ),
  ];

  List<ChartSampleData> heightStandardsForBoys = <ChartSampleData>[
    ChartSampleData(
      index: 0,
      y: 55.6,
      yValue: 44.2,
      secondSeriesYValue: 53.7,
      thirdSeriesYValue: 46.1,
      fourthSeriesYValue: 51.8,
      fifthSeriesYValue: 48.0,
      sixthSeriesYValue: 49.9,
    ),
    ChartSampleData(
      index: 1,
      y: 60.6,
      yValue: 48.9,
      secondSeriesYValue: 58.6,
      thirdSeriesYValue: 50.8,
      fourthSeriesYValue: 56.7,
      fifthSeriesYValue: 52.8,
      sixthSeriesYValue: 54.7,
    ),
    ChartSampleData(
      index: 2,
      y: 64.4,
      yValue: 52.4,
      secondSeriesYValue: 62.4,
      thirdSeriesYValue: 54.4,
      fourthSeriesYValue: 60.4,
      fifthSeriesYValue: 56.4,
      sixthSeriesYValue: 58.4,
    ),
    ChartSampleData(
      index: 3,
      y: 67.6,
      yValue: 55.3,
      secondSeriesYValue: 65.5,
      thirdSeriesYValue: 57.3,
      fourthSeriesYValue: 63.5,
      fifthSeriesYValue: 59.4,
      sixthSeriesYValue: 61.4,
    ),
    ChartSampleData(
      index: 4,
      y: 70.1,
      yValue: 57.6,
      secondSeriesYValue: 68.0,
      thirdSeriesYValue: 59.7,
      fourthSeriesYValue: 66.0,
      fifthSeriesYValue: 61.8,
      sixthSeriesYValue: 63.9,
    ),
    ChartSampleData(
      index: 5,
      y: 72.2,
      yValue: 59.6,
      secondSeriesYValue: 70.1,
      thirdSeriesYValue: 61.7,
      fourthSeriesYValue: 68.0,
      fifthSeriesYValue: 63.8,
      sixthSeriesYValue: 65.9,
    ),
    ChartSampleData(
      index: 6,
      y: 74.0,
      yValue: 61.2,
      secondSeriesYValue: 71.9,
      thirdSeriesYValue: 63.3,
      fourthSeriesYValue: 69.8,
      fifthSeriesYValue: 65.5,
      sixthSeriesYValue: 67.6,
    ),
    ChartSampleData(
      index: 7,
      y: 75.7,
      yValue: 62.7,
      secondSeriesYValue: 73.5,
      thirdSeriesYValue: 64.8,
      fourthSeriesYValue: 71.3,
      fifthSeriesYValue: 67.0,
      sixthSeriesYValue: 69.2,
    ),
    ChartSampleData(
      index: 8,
      y: 77.2,
      yValue: 64.0,
      secondSeriesYValue: 75.0,
      thirdSeriesYValue: 66.2,
      fourthSeriesYValue: 72.8,
      fifthSeriesYValue: 68.4,
      sixthSeriesYValue: 70.6,
    ),
    ChartSampleData(
      index: 9,
      y: 78.7,
      yValue: 65.2,
      secondSeriesYValue: 76.5,
      thirdSeriesYValue: 67.5,
      fourthSeriesYValue: 74.2,
      fifthSeriesYValue: 69.7,
      sixthSeriesYValue: 72.0,
    ),
    ChartSampleData(
      index: 10,
      y: 80.1,
      yValue: 66.4,
      secondSeriesYValue: 77.9,
      thirdSeriesYValue: 68.7,
      fourthSeriesYValue: 75.6,
      fifthSeriesYValue: 71.0,
      sixthSeriesYValue: 73.3,
    ),
    ChartSampleData(
      index: 11,
      y: 81.5,
      yValue: 67.6,
      secondSeriesYValue: 79.2,
      thirdSeriesYValue: 69.9,
      fourthSeriesYValue: 76.9,
      fifthSeriesYValue: 72.2,
      sixthSeriesYValue: 74.5,
    ),
  ];
  // height end

  // circle start
  List<ChartSampleData> circleStandardsForGirls = <ChartSampleData>[
    ChartSampleData(
      index: 0,
      y: 37.4,
      yValue: 30.3,
      secondSeriesYValue: 36.2,
      thirdSeriesYValue: 31.5,
      fourthSeriesYValue: 35.1,
      fifthSeriesYValue: 32.7,
      sixthSeriesYValue: 33.9,
    ),
    ChartSampleData(
      index: 1,
      y: 40.1,
      yValue: 33.0,
      secondSeriesYValue: 38.9,
      thirdSeriesYValue: 34.2,
      fourthSeriesYValue: 37.7,
      fifthSeriesYValue: 35.4,
      sixthSeriesYValue: 36.5,
    ),
    ChartSampleData(
      index: 2,
      y: 41.9,
      yValue: 34.6,
      secondSeriesYValue: 40.7,
      thirdSeriesYValue: 35.8,
      fourthSeriesYValue: 39.5,
      fifthSeriesYValue: 37.0,
      sixthSeriesYValue: 38.3,
    ),
    ChartSampleData(
      index: 3,
      y: 43.3,
      yValue: 35.8,
      secondSeriesYValue: 42.0,
      thirdSeriesYValue: 37.1,
      fourthSeriesYValue: 40.8,
      fifthSeriesYValue: 38.3,
      sixthSeriesYValue: 39.5,
    ),
    ChartSampleData(
      index: 4,
      y: 44.4,
      yValue: 36.8,
      secondSeriesYValue: 43.1,
      thirdSeriesYValue: 38.1,
      fourthSeriesYValue: 41.8,
      fifthSeriesYValue: 39.3,
      sixthSeriesYValue: 40.6,
    ),
    ChartSampleData(
      index: 5,
      y: 45.3,
      yValue: 37.6,
      secondSeriesYValue: 44.0,
      thirdSeriesYValue: 38.9,
      fourthSeriesYValue: 42.7,
      fifthSeriesYValue: 40.2,
      sixthSeriesYValue: 41.5,
    ),
    ChartSampleData(
      index: 6,
      y: 46.1,
      yValue: 38.3,
      secondSeriesYValue: 44.8,
      thirdSeriesYValue: 39.6,
      fourthSeriesYValue: 43.5,
      fifthSeriesYValue: 40.9,
      sixthSeriesYValue: 42.2,
    ),
    ChartSampleData(
      index: 7,
      y: 46.8,
      yValue: 38.9,
      secondSeriesYValue: 45.5,
      thirdSeriesYValue: 40.2,
      fourthSeriesYValue: 44.1,
      fifthSeriesYValue: 41.5,
      sixthSeriesYValue: 42.8,
    ),
    ChartSampleData(
      index: 8,
      y: 47.4,
      yValue: 39.4,
      secondSeriesYValue: 46.0,
      thirdSeriesYValue: 40.7,
      fourthSeriesYValue: 44.7,
      fifthSeriesYValue: 42.0,
      sixthSeriesYValue: 43.4,
    ),
    ChartSampleData(
      index: 9,
      y: 47.8,
      yValue: 39.8,
      secondSeriesYValue: 46.5,
      thirdSeriesYValue: 41.2,
      fourthSeriesYValue: 45.2,
      fifthSeriesYValue: 42.5,
      sixthSeriesYValue: 43.8,
    ),
    ChartSampleData(
      index: 10,
      y: 48.3,
      yValue: 40.2,
      secondSeriesYValue: 46.9,
      thirdSeriesYValue: 41.5,
      fourthSeriesYValue: 45.6,
      fifthSeriesYValue: 42.9,
      sixthSeriesYValue: 44.2,
    ),
    ChartSampleData(
      index: 11,
      y: 48.6,
      yValue: 40.5,
      secondSeriesYValue: 47.3,
      thirdSeriesYValue: 41.9,
      fourthSeriesYValue: 45.9,
      fifthSeriesYValue: 43.2,
      sixthSeriesYValue: 44.6,
    ),
  ];

  List<ChartSampleData> circleStandardsForBoys = <ChartSampleData>[
    ChartSampleData(
      index: 0,
      y: 38.3,
      yValue: 30.7,
      secondSeriesYValue: 37.0,
      thirdSeriesYValue: 31.9,
      fourthSeriesYValue: 35.7,
      fifthSeriesYValue: 33.2,
      sixthSeriesYValue: 34.5,
    ),
    ChartSampleData(
      index: 1,
      y: 40.8,
      yValue: 33.8,
      secondSeriesYValue: 39.6,
      thirdSeriesYValue: 34.9,
      fourthSeriesYValue: 38.4,
      fifthSeriesYValue: 36.1,
      sixthSeriesYValue: 37.3,
    ),
    ChartSampleData(
      index: 2,
      y: 42.6,
      yValue: 35.6,
      secondSeriesYValue: 41.5,
      thirdSeriesYValue: 36.8,
      fourthSeriesYValue: 40.3,
      fifthSeriesYValue: 38.0,
      sixthSeriesYValue: 39.1,
    ),
    ChartSampleData(
      index: 3,
      y: 44.1,
      yValue: 37.0,
      secondSeriesYValue: 42.9,
      thirdSeriesYValue: 38.1,
      fourthSeriesYValue: 41.7,
      fifthSeriesYValue: 39.3,
      sixthSeriesYValue: 40.5,
    ),
    ChartSampleData(
      index: 4,
      y: 45.2,
      yValue: 38.0,
      secondSeriesYValue: 44.0,
      thirdSeriesYValue: 39.2,
      fourthSeriesYValue: 42.8,
      fifthSeriesYValue: 40.4,
      sixthSeriesYValue: 41.6,
    ),
    ChartSampleData(
      index: 5,
      y: 46.2,
      yValue: 38.9,
      secondSeriesYValue: 45.0,
      thirdSeriesYValue: 40.1,
      fourthSeriesYValue: 43.8,
      fifthSeriesYValue: 41.4,
      sixthSeriesYValue: 42.6,
    ),
    ChartSampleData(
      index: 6,
      y: 47.0,
      yValue: 39.7,
      secondSeriesYValue: 45.8,
      thirdSeriesYValue: 40.9,
      fourthSeriesYValue: 44.6,
      fifthSeriesYValue: 42.1,
      sixthSeriesYValue: 43.3,
    ),
    ChartSampleData(
      index: 7,
      y: 47.7,
      yValue: 40.3,
      secondSeriesYValue: 46.4,
      thirdSeriesYValue: 41.5,
      fourthSeriesYValue: 45.2,
      fifthSeriesYValue: 42.7,
      sixthSeriesYValue: 44.0,
    ),
    ChartSampleData(
      index: 8,
      y: 48.3,
      yValue: 40.8,
      secondSeriesYValue: 47.0,
      thirdSeriesYValue: 42.0,
      fourthSeriesYValue: 45.8,
      fifthSeriesYValue: 43.3,
      sixthSeriesYValue: 44.5,
    ),
    ChartSampleData(
      index: 9,
      y: 48.8,
      yValue: 41.2,
      secondSeriesYValue: 47.5,
      thirdSeriesYValue: 42.5,
      fourthSeriesYValue: 46.3,
      fifthSeriesYValue: 43.7,
      sixthSeriesYValue: 45.0,
    ),
    ChartSampleData(
      index: 10,
      y: 49.2,
      yValue: 41.6,
      secondSeriesYValue: 47.9,
      thirdSeriesYValue: 42.9,
      fourthSeriesYValue: 46.7,
      fifthSeriesYValue: 44.1,
      sixthSeriesYValue: 45.4,
    ),
    ChartSampleData(
      index: 11,
      y: 49.6,
      yValue: 41.9,
      secondSeriesYValue: 48.3,
      thirdSeriesYValue: 43.2,
      fourthSeriesYValue: 47.0,
      fifthSeriesYValue: 44.5,
      sixthSeriesYValue: 45.8,
    ),
  ];
  // circle end
}
