name: repositories
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  cupertino_icons: ^1.0.2
  services:
    path: ../services
  models:
    path: ../models
  api_models:
    path: ../api_models
  shared:
    path: ../shared
  firebase_messaging: ^14.7.21
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
